kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "n8n.fullname" . }}
data:
  N8N_ENCRYPTION_KEY: {{ .Values.n8n.encryptionKey | required "encryptionKey is required to make sure u won't lose access to credentials" }}
  {{ if .Values.postgresql.enabled }}
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: {{ include "n8n.fullname" . }}-postgresql
  DB_POSTGRESDB_USER: {{ .Values.postgresql.auth.username }}
  DB_POSTGRESDB_DATABASE: {{ .Values.postgresql.auth.database }}
  DB_POSTGRESDB_PASSWORD: {{ .Values.postgresql.auth.password }}
  {{ end }}

  N8N_METRICS: "true"
  N8N_METRICS_PREFIX: "n8n_"

  QUEUE_BULL_REDIS_HOST: {{ include "n8n.fullname" . }}-redis-headless
  QUEUE_BULL_REDIS_PORT: "6379"
  QUEUE_BULL_REDIS_DB: "0"
  QUEUE_HEALTH_CHECK_ACTIVE: "true"
  QUEUE_HEALTH_CHECK_PORT: "5679"

  {{ if .Values.n8n.auth.enabled }}
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: {{ .Values.n8n.auth.username }}
  N8N_BASIC_AUTH_PASSWORD: {{ .Values.n8n.auth.password }}
  {{ end }}

  GENERIC_TIMEZONE: {{ .Values.n8n.timezone | default "UTC" }}
  
  WEBHOOK_URL: {{ .Values.n8n.webhookUrl | default "http://localhost" }}
  EXECUTIONS_MODE: "queue"
  N8N_DISABLE_PRODUCTION_MAIN_PROCESS: "true"
  OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: "true"

  EXECUTIONS_DATA_PRUNE: {{ .Values.n8n.data.prune.enabled | quote}}
  EXECUTIONS_DATA_MAX_AGE: {{ .Values.n8n.data.prune.max_age | quote }}

  N8N_LOG_LEVEL: {{ .Values.n8n.log_level | default "debug" | quote }}
  DB_LOGGING_ENABLED: {{ .Values.n8n.db_logging_enabled | default "true" | quote }}
  DB_LOGGING_OPTIONS: {{ .Values.n8n.db_logging_options | default "all" | quote }}
  
  {{- with .Values.n8n.extraEnvs }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  