name: Push Helm chart to OCI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        id: checkout
      - uses: azure/setup-helm@v4
        id: install_helm
      - name: Build Helm chart
        run: |
          helm package ./n8n
      - name: Login to Helm OCI
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ vars.OCI_REGISTRY }} --username ${{ github.repository_owner }} --password-stdin
      - name: Push Helm chart to OCI
        run: |
          helm push n8n-*.tgz oci://${{ vars.OCI_REGISTRY }}/${{ vars.OCI_REPOSITORY }}
      - name: Update README.md with Helm chart version
        run: |
          sed -i "s/--version .*/--version $(grep -oP '^version: \K.*' n8n/Chart.yaml)/" README.md
          rm n8n-*.tgz -f
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          message: "release: update README.md with Helm chart version"
          github_token: ${{ secrets.GITHUB_TOKEN }}
